-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 21:47:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UsergRPC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UsergRPC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UsergRPC` DEFAULT CHARACTER SET utf8 ;
USE `UsergRPC` ;

-- -----------------------------------------------------
-- Table `UsergRPC`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UsergRPC`.`Person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `PersonName` VARCHAR(45) NOT NULL,
  `PersonAge` VARCHAR(45) NOT NULL,
  `PersonMail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UsergRPC`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UsergRPC`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `UserPassword` VARCHAR(255) NOT NULL,
  `Person_idperson` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Person_idperson`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_User_Person_idx` (`Person_idperson` ASC) VISIBLE,
  CONSTRAINT `fk_User_Person`
    FOREIGN KEY (`Person_idperson`)
    REFERENCES `UsergRPC`.`Person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UsergRPC`.`Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UsergRPC`.`Logs` (
  `idLogs` INT NOT NULL AUTO_INCREMENT,
  `LoginLog` TIMESTAMP NOT NULL,
  `User_idUser` INT NOT NULL,
  `User_Person_idperson` INT NOT NULL,
  PRIMARY KEY (`idLogs`, `User_idUser`, `User_Person_idperson`),
  INDEX `fk_Logs_User1_idx` (`User_idUser` ASC, `User_Person_idperson` ASC) VISIBLE,
  CONSTRAINT `fk_Logs_User1`
    FOREIGN KEY (`User_idUser` , `User_Person_idperson`)
    REFERENCES `UsergRPC`.`User` (`idUser` , `Person_idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
