# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"O\n\x16\x41uthenticationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"g\n\x17UserCredentialsRegister\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"L\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08mensagge\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2V\n\x15\x41uthenticationService\x12=\n\x10\x41uthenticateUser\x12\x10.UserCredentials\x1a\x17.AuthenticationResponse2N\n\x0fRegisterService\x12;\n\x0cRegisterUser\x12\x18.UserCredentialsRegister\x1a\x11.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERCREDENTIALS']._serialized_start=14
  _globals['_USERCREDENTIALS']._serialized_end=67
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=69
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=148
  _globals['_USERCREDENTIALSREGISTER']._serialized_start=150
  _globals['_USERCREDENTIALSREGISTER']._serialized_end=253
  _globals['_REGISTERRESPONSE']._serialized_start=255
  _globals['_REGISTERRESPONSE']._serialized_end=331
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=333
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=419
  _globals['_REGISTERSERVICE']._serialized_start=421
  _globals['_REGISTERSERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
